name: CMake build RokerPack VST3 plugins

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release
  PLUGINS: "Bronza Grelka Metalluga Charm Tembr Mistral GuitarTuner BassTuner"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y git make g++ cmake pkg-config \
            libasound2-dev libjack-jackd2-dev ladspa-sdk \
            libcurl4-openssl-dev libfreetype6-dev libx11-dev \
            libxcomposite-dev libxcursor-dev libxext-dev \
            libxinerama-dev libxrandr-dev libxrender-dev \
            libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build all plugins
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create ZIP with plugins
      run: |
        # Создаём временную директорию с нужным именем
        mkdir -p ${{github.workspace}}/RokerPack_${{env.BUILD_TYPE}}
        
        # Копируем плагины
        for plugin in ${{env.PLUGINS}}; do
          echo "Copying $plugin..."
          src_path="${{github.workspace}}/build/${plugin}_artefacts/${{env.BUILD_TYPE}}/VST3/${plugin}.vst3"
          if [ -d "$src_path" ]; then
            cp -r "$src_path" ${{github.workspace}}/RokerPack_${{env.BUILD_TYPE}}/
          else
            echo "Warning: ${plugin}.vst3 not found at $src_path"
          fi
        done
        
        # Архивируем ВСЮ папку
        cd ${{github.workspace}}
        zip -r RokerPack_${{env.BUILD_TYPE}}.zip RokerPack_${{env.BUILD_TYPE}}
        
        # Удаляем временную папку
        rm -rf RokerPack_${{env.BUILD_TYPE}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: RokerPack_${{env.BUILD_TYPE}}
        path: ${{github.workspace}}/RokerPack_${{env.BUILD_TYPE}}.zip
        retention-days: 30